<a href="https://colab.research.google.com/github/dsairreddy/ML/blob/main/NumPy_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install numpy -
#.    pip3 install numpy // pip install numpy
# speed (list operations)< speed(Numpy operations)
# Memory optimization (numpy) > memory optimization (
)

In [ ]:
import numpy as np

In [ ]:
# Create a Numpy Array
# 1D Array
arr1D = np.array([1,2,3,4,5])
arr1D

array([1, 2, 3, 4, 5])

In [ ]:

# Create 2d Array - Matrix
# 2D Array - ([A],
#             [B])
arr2D = np.array([[1,2,3],[4,5,6]])
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Creating Arrays with default or
#.  Same values
# Creating matrix with ones
allZER0S = np.zeros((2,3))

AllOnes = np.ones((2,3))
AllOnes

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# create constant values 'n'
AllConstant = np.full((2,3),6)
AllConstant

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
# Creating
# Identity Matrix - Aii = 1 && Aij =0
# For all A belongs to R M×N
# Aij -
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Random Matrix
# vales between 0 and 1
rand1 = np.random.rand(3,3)
rand1

array([[0.72382132, 0.10121128, 0.72845422],
       [0.16747856, 0.61503051, 0.06777732],
       [0.60593406, 0.08907119, 0.7577064 ]])

In [ ]:
# between a and b
rand2 = np.random.randint(10,20,(3,3))
rand2

array([[15, 16, 15],
       [19, 19, 13],
       [16, 11, 12]])

In [ ]:
# Array properties
# shape or Array
# size of Array
# datatype of array
# dimensions of Array
arr= np.array([[1,2,3,4],[5,6,7,8]])
print(f'\nthe shape of array {arr.shape}')


the shape of array (2, 4)


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.size

8

In [ ]:
arr.ndim #dimention

2

In [ ]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.11/dist-packages/numpy/version.py'>

In [ ]:
# indexing and Slicing
# Accessing the elements in 1D Array
arR = np.array([1,2,3,4])
arR[1]

2

In [ ]:
# Slicing elements
arR[0:3]

array([1, 2, 3])

In [ ]:
# accessing
arr2D[1,1]

array([1, 2, 3])

In [ ]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2D[0,:] #first row all columns

array([1, 4])

In [ ]:
arr2D[:,0] #first column all rows

array([1, 4])

In [63]:
L1 = []
L1= np.arange(10,-10,-1)
L1
#[L1.append(_) for _ in range(10)]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6,
       -7, -8, -9])

In [69]:
# Mathematical Operations
a = np.array([1,2,3])
b = np.array([3,4,5])
a - b
a+b
a*b
a/b

array([0.33333333, 0.5       , 0.6       ])

In [75]:
# Matrix multiplication 2D
B1 = np.array([[1,2,3],[2,3,4]])
B2 = np.array([[5,6],[5,7],[6,7]])
# "dot" product
c = np.dot(B1,B2)
c

array([[33, 41],
       [49, 61]])

In [76]:
B1

array([[1, 2, 3],
       [2, 3, 4]])

In [77]:
B2

array([[5, 6],
       [5, 7],
       [6, 7]])