<a href="https://colab.research.google.com/github/dsairreddy/ML/blob/main/NumPy_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
R1 = np.eye(4)
R1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
R2 = np.random.randint(10,20,(4,4))
R2

array([[10, 18, 11, 12],
       [13, 12, 10, 14],
       [11, 16, 12, 12],
       [18, 18, 15, 15]])

In [ ]:
Res = np.dot(R1,R2)
Res
# M . I = I . M = M

array([[10., 18., 11., 12.],
       [13., 12., 10., 14.],
       [11., 16., 12., 12.],
       [18., 18., 15., 15.]])

In [ ]:
# Mathematical Operations
# + - * /
T2 = np.random.randint(3,6,(3,3))
T1 = np.random.randint(3,6,(3,3))
T3 = T1 * T2
T3

array([[25, 25, 20],
       [20, 15, 20],
       [15, 12, 12]])

In [ ]:

# Statistical Operations
T3.mean()

T3.max()
np.median(T3)
Std = np.std(T3) # standard deviations 'std'
np.var(T3)

16.22222222222222

In [ ]:
Std*Std # is equal to std

16.22222222222222

In [ ]:
# Trigonometric functions
# sin(x)
# cos(x)
# tan(x)
# cosec(x) - 1 / sin(x)
# sec(x) - 1 / cos(x)
# cot(x) - 1 / tan(x)
angles= np.array([10,20,30,40,50,60,70])
np.sin(np.radians(angles))
np.tan(np.radians(angles))
np.cos(np.radians(angles))

array([0.98480775, 0.93969262, 0.8660254 , 0.76604444, 0.64278761,
       0.5       , 0.34202014])

In [ ]:
# change array shape
# .reshape()

array = np.array([1,2,3,4,5,6])
array= array.reshape(3,2)
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# convert or flatten any n dim array
array.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Stacking Data
# Helps to attach 2 arrays
# 1. Vstack 2. Hstack
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])

arr3 = np.vstack((arr1,arr2))
arr3.shape

(2, 4)

In [ ]:
arr4 = np.hstack((arr1,arr2))
arr4

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
# Filtering
arr= np.array([1,2,3,42,6,7,8])
Farr= arr[arr > 40]
Farr

array([42])